version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    day: thursday
    interval: weekly
    time: "05:30"
    timezone: Europe/London
  reviewers:
    - "martincostello"
